import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Nome Que Aparece na Aba",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div>ISSO É UM CABEÇALHO COMUM PARA QUALQUER PAGINA DA APLICAÇÃO</div>
        {children}
        </body>
    </html>
  );
}
